/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sunyu' at '8/22/17 3:38 PM' with Gradle 2.14.1
 *
 * @author sunyu, @date 8/22/17 3:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
